http:
  enabled: true
  debugEndpoints: true
#   tls:
#     enabled: true
#     secretName: benthos-test-tls
service:
  ports: 
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: wheee
    port: 12345
    targetPort: http
    protocol: TCP
streams:
  enabled: true
  streamsConfigMap: "test-benthos-streams"
  api:
    enable: false