name: helm_release

on: 
  push:
    branches:
      - main

jobs:
  helm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: .
          charts_repo_url: https://benthosdev.github.io/benthos-helm-chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sync readme to gh-pages
        env:
          pages_branch: gh-pages
          target_branch: main
        run: |
          git checkout ${{ env.target_branch }}
          cp -v README.md ..
          git checkout ${{ env.pages_branch }}
          mv -v ../README.md .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "sync README"
          git push origin ${{ env.pages_branch }}
